### ISSUE TITLE
Хайх товчийг эхний удаа дархад ажиллахгүй байна.

### ISSUE THREAD

**Issue by hurelhuyag** [swganzo/bolor-tolidogch#2]
Хайх талбарт үгээ бичээд томруулдаг шилний зурагтай товчийг эхний удаа дархад ажиллахгүй байна.  Enter товч ч бас эхний удаад ажиллахгүй байна.

**Comment by swganzo** [comment]
За засаад хэлье.

**Comment by swganzo** [comment]
Засчихсан шүү
